### PR TITLE
Russian translation added

### PR DESCRIPTION
**Pull request by Vadimbhai**

### CODE REVIEW

**Comment by nickyoung87** [comment]
Thanks for your contribution!

**Comment by nickyoung87** [comment]
@Vadimbhai,

Can you actually provide me with a couple things so that I can add the credit into the README?

1. Name you would like to have displayed.
2. Your website URL if you have one.

If you would feel more comfortable emailing me the info you can feel free to send it to: mycorpweb@gmail.com

Thanks!

**Comment by Vadimbhai** [comment]
Hi, Nick!

It was not very hard for me, and I need that translation for my site - this is the main reason of :)
But if you want, you can write my name - Vadim Reutskiy, without URL (because I do not have one for now).

**Comment by nickyoung87** [comment]
Thank you for getting back to me. We love to give credit where it's due :)

Thanks again!

**Pull request merged**
